# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dustin Alandzes
tagline:          'Person.'
description:      'Person.'
url:              http://dustin.alandz.es
baseurl:          /

author:
  name:           'Dustin Alandzes'
  url:            http://alandz.es/

paginate:         5

# Custom vars
version:          2.1.0
github:           http://girhub.com/f00-
