/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 window_blinds_low_poly_3d_model.glb --transform --types 
Files: window_blinds_low_poly_3d_model.glb [1.71MB] > /Users/dustinalandzes/PycharmProjects/DustinAlandzes.github.io/frontend/public/window_blinds_low_poly_3d_model-transformed.glb [94.25KB] (94%)
Author: AHMED KCHIKICH (https://sketchfab.com/inven2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-blinds-low-poly-3d-model-642df0acc18f45d2af8eaa698bdccff7
Title: Window Blinds Low poly 3D model
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Blinds: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/window_blinds_low_poly_3d_model-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Blinds} position={[-294.612, 164.329, -199.939]} />
    </group>
  )
}

useGLTF.preload('/window_blinds_low_poly_3d_model-transformed.glb')
