name: DeployBackend
on:
  workflow_run:
    workflows: [ PythonTest ]
    branches:
      - master
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Dependencies
        run: pip install -r requirements.txt -t ./package  --platform manylinux2014_x86_64 --only-binary=:all
      - name: Archive the lambda function code and dependencies
        run: cp main.py package/main.py && zip -r ../deployment_package.zip package
      - name: Push code to lambda
        run: aws lambda update-function-code --function-name ${{ env.AWS_LAMBDA_FUNCTION_ARN }} --zip-file fileb://deployment_package.zip